/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.punchcafe.arcane;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        //assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}

// generate a map of classes to their dependency names. allow searching of the whole thing to discover. use
// use the map to look up generation, as opposed to just relying on the class
