/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.punchcafe.arcane;

import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException {
        // TODO: refactor to use class path here
        String dirName = ".";

        final var spellBook = SpellBook.threadSpellBook(dirName);

        final var dependee = spellBook.summon(Dependee.class);
        System.out.println("End");
        return;
    }
}



